// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyufBgIZLt41CVsNkQ-DtPiO_kygV8OuA',
    appId: '1:690539220658:web:d28424bade17d58441c3ab',
    messagingSenderId: '690539220658',
    projectId: 'billsnap-ac4cd',
    authDomain: 'billsnap-ac4cd.firebaseapp.com',
    storageBucket: 'billsnap-ac4cd.firebasestorage.app',
    measurementId: 'G-EX50ESZ041',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABaPfCH5I5ByP0HppHZkSK0I5IwqFViP0',
    appId: '1:690539220658:android:77a206952f73f47b41c3ab',
    messagingSenderId: '690539220658',
    projectId: 'billsnap-ac4cd',
    storageBucket: 'billsnap-ac4cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCinuaNqFMEoibFAEBGwVxIsBuRsKgjyHU',
    appId: '1:690539220658:ios:f25be3959da6d84e41c3ab',
    messagingSenderId: '690539220658',
    projectId: 'billsnap-ac4cd',
    storageBucket: 'billsnap-ac4cd.firebasestorage.app',
    iosBundleId: 'com.example.billSnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCinuaNqFMEoibFAEBGwVxIsBuRsKgjyHU',
    appId: '1:690539220658:ios:f25be3959da6d84e41c3ab',
    messagingSenderId: '690539220658',
    projectId: 'billsnap-ac4cd',
    storageBucket: 'billsnap-ac4cd.firebasestorage.app',
    iosBundleId: 'com.example.billSnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyufBgIZLt41CVsNkQ-DtPiO_kygV8OuA',
    appId: '1:690539220658:web:72526969e1d6f94c41c3ab',
    messagingSenderId: '690539220658',
    projectId: 'billsnap-ac4cd',
    authDomain: 'billsnap-ac4cd.firebaseapp.com',
    storageBucket: 'billsnap-ac4cd.firebasestorage.app',
    measurementId: 'G-LPT7E9H9EE',
  );
}
